### ISSUE TITLE
404 page( path='/*'), footer & header 숨기기

### ISSUE THREAD

**Issue by NickYOOO** [NickYOOO/Please#1]
## 이슈 개요
- NotFoundPage 에서 footer 를 숨기려고 했으나 숨겨지지 않음
## 상세 내용

![스크린샷 2023-07-19 오전 12 54 41](https://github.com/NickYOOO/UHR/assets/108923582/85d0f8eb-ca5e-44a4-89fd-18c0adae4781)
NotFoundPage  경로에서 footer를 숨기려고 시도.
![스크린샷 2023-07-19 오전 12 58 52](https://github.com/NickYOOO/UHR/assets/108923582/db3b8593-6689-4004-aad3-43bd84478554)
그러나 와일드카드 문자로 이루어진 경로 에서는 적용되지 않는 문제

**Comment by NickYOOO** [comment]
## 해결 제안
```typescript
if (
  window.location.pathname !== '/signup' &&
  window.location.pathname !== '/login' &&
  window.location.pathname !== '/' &&
  window.location.pathname !== '/post' &&
  window.location.pathname !== '/board' &&
  window.location.pathname !== '/detail/:id' &&
  window.location.pathname !== '/user/:id' &&
  window.location.pathname !== '/report'
) {
  return null;
}
```

## 상세내용

와일드카드 문자 경로가 적용되지 않아, 나머지 경로로 조건을 주었습니다.

**Comment by bender9507** [comment]
## 해결 제안

좀 더 간략하게 써보면 어떨까요?
```typescript
if (!['/signup', '/login', '/', '/post', '/board', '/detail/:id', '/user/:id', '/report'].includes(window.location.pathname)) return null;
```

**Comment by NickYOOO** [comment]
수빈님 코드가 더 간결하고 좋아보이네요! 수빈님 코드로 수정하겠습니다!

**Comment by oiooeo** [comment]
상세페이지 /detail/1 이 경로로 들어가면 헤더 푸터 안뜹니다 ,,, user 페이지도 마찬가지입니닷
/detail/:id, /user:/id 예외 처리 되나봐요 😇

**Comment by oiooeo** [comment]
정규식으로 해결했습니다!

**Comment by NickYOOO** [comment]
고생하셨습니다!
