### ISSUE TITLE
유저 닉네임 길이에 따른 UI 문제

### ISSUE THREAD

**Issue by Rimsunwoo** [NickYOOO/Please#36]
![image](https://github.com/NickYOOO/Please/assets/92662974/7191e477-3fe0-495f-93c3-e9178fef099c)
유저 닉네임이 4글자 이상 넘어갈 때 헤더에서 줄바꿈되는 버그가 있습니다

**Comment by bender9507** [comment]
원래 계획했던 Ui로 수정하면 문제 해결될 것 같습니다!
![image](https://github.com/NickYOOO/Please/assets/125546973/ab331825-39d3-4e80-892a-9933518b6674)

**Comment by NickYOOO** [comment]
해결 완료 했습니다! 
---
![스크린샷 2023-08-13 오후 5 22 48](https://github.com/NickYOOO/Please/assets/108923582/98559b5f-03e4-463c-b95d-a3aab88ea19d)
